services:
  database:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ecoride_db
    ports:
      - "3307:3306"

  php:
    build: .
    container_name: ecoride_app
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://root:@database:3306/ecoride_db?serverVersion=8.0&charset=utf8mb4"


  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ecoride_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database